batch_size: 16
config: ./config/mnist.yaml
confusion_prefix: ''
depth_ignore_weights: []
depth_model: null
depth_model_args: {}
depth_weights: null
device: 0
eval_interval: 5
feeder: feeder.BaseFeeder
ignore_weights: []
log_interval: 100
model: models.LeNet5
model_args:
  num_classes: 10
num_epoch: 10
num_worker: 10
optimizer_args:
  base_lr: 0.01
  nesterov: false
  optimizer: SGD
  start_epoch: 0
  step:
  - 5
  - 8
  weight_decay: 0.005
phase: train
print_log: true
random_fix: true
random_seed: 0
save_interval: 5
test_batch_size: 16
test_feeder_args:
  data_path: /home/myc/Datasets/MNIST/t10k-images-idx3-ubyte.gz
  label_path: /home/myc/Datasets/MNIST/t10k-labels-idx1-ubyte.gz
timesteps: []
train_feeder_args:
  data_path: /home/myc/Datasets/MNIST/train-images-idx3-ubyte.gz
  label_path: /home/myc/Datasets/MNIST/train-labels-idx1-ubyte.gz
valid_feeder_args: {}
weights: null
work_dir: ./work_dir/mnist
