feeder: feeder.BaseFeeder
phase: train
work_dir: ./work_dir/mnist
num_worker: 10
device: 0
log_interval: 100
eval_interval: 5
save_interval: 5

batch_size: 16
test_batch_size: 16
num_epoch: 10
#weights: ./work_dir/mnist/epoch10_model.pt

optimizer_args:
  optimizer: SGD
  base_lr: 0.01
  step: [ 5, 8]
  weight_decay: 0.005
  start_epoch: 0
  nesterov: False

train_feeder_args:
  data_path: "/home/myc/Datasets/MNIST/train-images-idx3-ubyte.gz"
  label_path: "/home/myc/Datasets/MNIST/train-labels-idx1-ubyte.gz"

test_feeder_args:
  data_path: "/home/myc/Datasets/MNIST/t10k-images-idx3-ubyte.gz"
  label_path: "/home/myc/Datasets/MNIST/t10k-labels-idx1-ubyte.gz"

model: models.LeNet5
model_args:
  num_classes: 10